/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentmgmt.gui;

import studentmgmt.dbutil.DBConnection;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class OptionFrame extends javax.swing.JFrame {

    /**
     * Creates new form SelectYourChoice
     */
    public OptionFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jrbAddStudent = new javax.swing.JRadioButton();
        jrbSearchStudent = new javax.swing.JRadioButton();
        jrbShowAllStudent = new javax.swing.JRadioButton();
        btnDoTask = new javax.swing.JButton();
        jrbupdateStudent = new javax.swing.JRadioButton();
        jrbDeleteStudent = new javax.swing.JRadioButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Select An Option");

        jrbAddStudent.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jrbAddStudent);
        jrbAddStudent.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jrbAddStudent.setForeground(new java.awt.Color(255, 255, 255));
        jrbAddStudent.setText("Add Student");

        jrbSearchStudent.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jrbSearchStudent);
        jrbSearchStudent.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jrbSearchStudent.setForeground(new java.awt.Color(255, 255, 255));
        jrbSearchStudent.setText("Search Student");

        jrbShowAllStudent.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jrbShowAllStudent);
        jrbShowAllStudent.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jrbShowAllStudent.setForeground(new java.awt.Color(255, 255, 255));
        jrbShowAllStudent.setText("See All Student");

        btnDoTask.setBackground(new java.awt.Color(0, 0, 0));
        btnDoTask.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnDoTask.setForeground(new java.awt.Color(255, 255, 255));
        btnDoTask.setText("Do Task");
        btnDoTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoTaskActionPerformed(evt);
            }
        });

        jrbupdateStudent.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jrbupdateStudent);
        jrbupdateStudent.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jrbupdateStudent.setForeground(new java.awt.Color(255, 255, 255));
        jrbupdateStudent.setText("Update Student");

        jrbDeleteStudent.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jrbDeleteStudent);
        jrbDeleteStudent.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jrbDeleteStudent.setForeground(new java.awt.Color(255, 255, 255));
        jrbDeleteStudent.setText("Delete Student");

        btnBack.setBackground(new java.awt.Color(0, 0, 0));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrbShowAllStudent)
                            .addComponent(jrbSearchStudent)
                            .addComponent(jrbAddStudent)
                            .addComponent(jrbupdateStudent)
                            .addComponent(jrbDeleteStudent))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnDoTask)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(jLabel1)
                .addGap(107, 107, 107))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jrbAddStudent)
                .addGap(27, 27, 27)
                .addComponent(jrbSearchStudent)
                .addGap(26, 26, 26)
                .addComponent(jrbShowAllStudent)
                .addGap(27, 27, 27)
                .addComponent(jrbupdateStudent)
                .addGap(26, 26, 26)
                .addComponent(jrbDeleteStudent)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDoTask)
                    .addComponent(btnBack))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDoTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoTaskActionPerformed
        if(validateInput()==false){
            JOptionPane.showMessageDialog(null,"Please select an option");
            return;
        }
        JFrame frame=null;
        if(jrbAddStudent.isSelected()){
           frame=new AddStudentFrame();     
        }
        else if(jrbSearchStudent.isSelected()){
           frame=new SearchStudentFrame();  
        }
        else if(jrbShowAllStudent.isSelected()){
            frame=new ViewAllStudentFrame();
        }
        else if(jrbupdateStudent.isSelected()){ 
           frame=new UpdateStudentFrame();
        }
        else if(jrbDeleteStudent.isSelected()){   
           frame=new DeleteStudentFrame();
        }
         this.dispose();
         frame.setVisible(true);
    }//GEN-LAST:event_btnDoTaskActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        LoginFrame opFrame=new LoginFrame();
        opFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OptionFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDoTask;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jrbAddStudent;
    private javax.swing.JRadioButton jrbDeleteStudent;
    private javax.swing.JRadioButton jrbSearchStudent;
    private javax.swing.JRadioButton jrbShowAllStudent;
    private javax.swing.JRadioButton jrbupdateStudent;
    // End of variables declaration//GEN-END:variables

    private boolean validateInput() {
        if(jrbAddStudent.isSelected()==false&& jrbSearchStudent.isSelected()==false&& jrbShowAllStudent.isSelected()==false&&jrbupdateStudent.isSelected()==false&&jrbDeleteStudent.isSelected()==false)
               return false;
              return true;
        }
}
